(when (display-graphic-p)
  (tool-bar-mode -1)
  (when (locate-library "color-theme")
    (load (concat (file-name-directory load-file-name) "molokai-theme/color-theme-molokai.el"))
    (color-theme-molokai)))
